version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
